In [1]:
import numpy as np
import pypianoroll

In [29]:
pianoroll = np.random.randint(0, 127, (96, 128))
track = pypianoroll.Track(pianoroll, lowest=0)
multitrack = pypianoroll.Multitrack(tracks=[track],tempo=120.0)
pianoroll

array([[ 38,  32, 112, ...,  10,  41,  49],
       [ 81,  38,  42, ..., 125, 117, 117],
       [ 64,  52, 119, ..., 115, 106,  73],
       ..., 
       [ 44,  45,  45, ...,  33,  99,  12],
       [ 87,  77,  37, ...,  53,  92,  37],
       [ 33, 102, 115, ..., 125,  30, 108]])

In [22]:
track.clip(20, 100)
pianoroll

array([[  8,  80,  62, ...,  83,  18, 111],
       [ 71,  91,  57, ...,  91,  45,  84],
       [ 17, 120,  29, ...,  79,  19,  15],
       ..., 
       [118,  35,  38, ...,  67,  39,  77],
       [ 57,  63,  34, ...,  42,  34,  82],
       [115,  60,  21, ..., 100,  11,  81]])

In [23]:
multitrack.clip(40, 80)
pianoroll

array([[  8,  80,  62, ...,  83,  18, 111],
       [ 71,  91,  57, ...,  91,  45,  84],
       [ 17, 120,  29, ...,  79,  19,  15],
       ..., 
       [118,  35,  38, ...,  67,  39,  77],
       [ 57,  63,  34, ...,  42,  34,  82],
       [115,  60,  21, ..., 100,  11,  81]])

In [30]:
track.pianoroll[:,:10] = 0 # set the velocites of notes with the lowest two pitches to zero
track.pianoroll[:,-5:] = 0 # set the velocites of notes with the highest pitch to zero
track.compress_to_active()
print track.pianoroll.shape, track.lowest

(96L, 113L) 10


In [31]:
track.pianoroll[:,:2] = 0 # set the velocites of notes with the lowest five pitches to zero
track.pianoroll[:,-3:] = 0 # set the velocites of notes with the highest ten pitches to zero
multitrack.compress_to_active()
print track.pianoroll.shape, track.lowest

(96L, 93L) 20


In [26]:
track.expand(20, 60)
print track.pianoroll.shape, track.lowest

(96L, 41L) 20


In [19]:
multitrack.expand(0, 127)
print track.pianoroll.shape, track.lowest

(96L, 128L) 0
